[package]
name = "robigus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]
members = ["apps/robigus-ui", "apps/robigus-ui-web"]
